rnamaker_home:
    pattern:  /
    defaults: { _controller: HillCMSRnaMakerBundle:Default:index }
amirnadesigner_results:
    pattern: /amirna/designerresults/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amiRNADesignerResults }
amirnadesigner_results_plain:
    pattern: /amirna/designerresults
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amiRNADesignerResults }
rnamaker_about:
    pattern: /about
    defaults: { _controller: HillCMSRnaMakerBundle:Default:about }
rnamaker_faq:
    pattern: /faq
    defaults: { _controller:  HillCMSRnaMakerBundle:Default:faq}
rnamaker_amirnadesigner:
    pattern: /amirna/designer
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amirnaDesignerForm }
rnamaker_amirnarequest:
    pattern: /amirna/request
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amirnaDesignerRequest }
rnamaker_oligodesigner:
    pattern: /amirna/oligodesigner
    defaults: { _controller: HillCMSRnaMakerBundle:Default:oligoRequest }
rnamaker_targetfinder:
    pattern: /targetfinder/finder
    defaults: { _controller: HillCMSRnaMakerBundle:Default:targetFinderForm }
rnamaker_targetfinderrequest:
    pattern: /targetfinder/request
    defaults: { _controller: HillCMSRnaMakerBundle:Default:targetFinderRequest}
rnamaker_oligorequest: 
    pattern: /amiRNA_suite/oligorequest
    defaults: { _controller: HillCMSRnaMakerBundle:amiRNASuite:oligoRequest }
oligo_result_token:
    pattern: /amirna/oligoresults/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:Default:oligoResults }
oligo_result_token_plain:
    pattern: /amirna/oligoresults
    defaults: { _controller: HillCMSRnaMakerBundle:Default:results }
rnamaker_syntasidesigner:
    pattern: /syntasi/designer
    defaults: { _controller: HillCMSRnaMakerBundle:Default:syntasiDesignerForm }
rnamaker_syntasirequest:
    pattern: /syntasi/request
    defaults: { _controller: HillCMSRnaMakerBundle:Default:syntasirnaDesignerRequest }
syntasirnadesigner_results_plain:
    pattern: /syntasi/designerresults
    defaults: { _controller: HillCMSRnaMakerBundle:Angular:syntasiRNADesignerResults }
syntasirnadesigner_results:
    pattern: /syntasi/designerresults/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:Angular:syntasiRNADesignerResults }
psams_databases_data:
    pattern: /psams/databases
    defaults: { _controller: HillCMSRnaMakerBundle:Default:psamsDatabases }
syntasiresults_data:
    pattern: /syntasi/angular/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:Angular:syntasiResultsData }
