rnamaker_home:
    pattern:  /
    defaults: { _controller: HillCMSRnaMakerBundle:Default:index }
dummy_route:
    pattern: /dummy
    defaults: { _controller: HillCMSRnaMakerBundle:Default:dummy}
amirnadesigner_results:
    pattern: /amirna/designerresults/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amiRNADesignerResults }
amirnadesigner_results_plain:
    pattern: /amirna/designerresults
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amiRNADesignerResults }
rnamaker_amirnadesigner:
    pattern: /amirna/designer
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amirnaDesignerForm }
rnamaker_amirnarequest:
    pattern: /amirna/request
    defaults: { _controller: HillCMSRnaMakerBundle:Default:amirnaDesignerRequest }
rnamaker_targetfinder:
    pattern: /targetfinder/finder
    defaults: { _controller: HillCMSRnaMakerBundle:Default:targetFinderForm }
rnamaker_targetfinderrequest:
    pattern: /targetfinder/request
    defaults: { _controller: HillCMSRnaMakerBundle:Default:targetFinderRequest}
rnamaker_oligodesigner:
    pattern: /amiRNA_suite/oligodesigner
    defaults: { _controller: HillCMSRnaMakerBundle:amiRNASuite:oligoDesignerForm }
rnamaker_oligorequest: 
    pattern: /amiRNA_suite/oligorequest
    defaults: { _controller: HillCMSRnaMakerBundle:amiRNASuite:oligoRequest }
result_token:
    pattern: /amiRNA_suite/results/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:amiRNASuite:results}
result_token_plain:
    pattern: /amiRNA_suite/results
    defaults: { _controller: HillCMSRnaMakerBundle:amiRNASuite:results }
rnamaker_syntasidesigner:
    pattern: /syntasi/designer
    defaults: { _controller: HillCMSRnaMakerBundle:syntasiRNASuite:syntasiOligoDesignerform }
rnamaker_syntasi_oligodesigner:
    pattern: /syntasiRNA_suite/oligodesigner
    defaults: { _controller: HillCMSRnaMakerBundle:syntasiRNASuite:syntasiOligoDesignerForm }
rnamaker_syntasi_oligorequest:
    pattern: /syntasiRNA_suite/oligorequest
    defaults: { _controller: HillCMSRnaMakerBundle:syntasiRNASuite:syntasiOligoRequest }
rnamaker_syntasi_results:
    pattern: /syntasiRNA_suite/results/{token}
    defaults: { _controller: HillCMSRnaMakerBundle:syntasiRNASuite:syntasiResults}
rnamaker_syntasi_results_plain:
    pattern: /syntasiRNA_suite/results
    defaults: { _controller: HillCMSRnaMakerBundle:syntasiRNASuite:syntasiResults}

