parameters:
#    hill_cms_rna_maker.example.class: HillCMS\RnaMakerBundle\Example

services:
#    hill_cms_rna_maker.example:
#        class: %hill_cms_rna_maker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
